// Nook — Lightweight Local Plugin System
// Extends Notch actions: Obsidian Vault Sync, Todo.txt, and macOS/Windows Local Shortcuts

import { Meeting, ActionItem } from '../types';

export interface NookPlugin {
  id: string;
  name: string;
  description: string;
  icon: string;
  execute: (meeting: Meeting, actionItems?: ActionItem[]) => Promise<{ success: boolean; message: string }>;
}

export class PluginEngine {
  private plugins: Map<string, NookPlugin> = new Map();

  constructor() {
    this.registerDefaultPlugins();
  }

  private registerDefaultPlugins() {
    // 1. Obsidian Vault Sync Plugin
    this.registerPlugin({
      id: 'plugin-obsidian',
      name: 'Obsidian Vault',
      description: 'Syncs notes with YAML frontmatter, backlinks [[links]], and dataview tags.',
      icon: '💎',
      execute: async (meeting: Meeting) => {
        try {
          const frontmatter = [
            '---',
            `title: "${meeting.title}"`,
            `date: ${new Date(meeting.startedAt).toISOString().split('T')[0]}`,
            `type: meeting`,
            `template: ${meeting.templateType}`,
            `duration_min: ${Math.floor(meeting.durationSeconds / 60)}`,
            `score: ${meeting.meetingScore || 95}`,
            `tags: [meeting, ${meeting.templateType}, ${(meeting.tags || []).join(', ')}]`,
            '---',
            '',
            `# [[${meeting.title}]]`,
            '',
            `## Summary`,
            meeting.executiveSummary,
            '',
            `## ⚡ Critical Decisions`,
            ...(meeting.keyDecisions || []).map((d) => `- [x] #decision ${d}`),
            '',
            `## 🎯 Action Items`,
            ...(meeting.actionItems || []).map((a) => `- [${a.completed ? 'x' : ' '}] #task ${a.task} ^owner(${a.assignee})`),
            '',
            `## 🧠 Key Takeaways`,
            ...(meeting.rememberedParts || []).map((r) => `- #memory ${r}`),
            '',
            `---`,
            `*Generated by Nook Notch Local Intelligence*`,
          ].join('\n');

          const blob = new Blob([frontmatter], { type: 'text/markdown;charset=utf-8' });
          const url = URL.createObjectURL(blob);
          const link = document.createElement('a');
          link.href = url;
          link.download = `${meeting.title.toLowerCase().replace(/[^a-z0-9]/g, '-')}.md`;
          link.click();
          URL.revokeObjectURL(url);

          return { success: true, message: `Synced "${meeting.title}" to Obsidian markdown format!` };
        } catch (err: any) {
          return { success: false, message: `Obsidian sync failed: ${err.message}` };
        }
      },
    });

    // 2. Todo.txt Standard Plugin
    this.registerPlugin({
      id: 'plugin-todotxt',
      name: 'Todo.txt',
      description: 'Formats and exports open action items into standard (A) priority todo.txt entries.',
      icon: '📋',
      execute: async (meeting: Meeting) => {
        try {
          const dateStr = new Date().toISOString().split('T')[0];
          const lines = (meeting.actionItems || []).map((a) => {
            const priorityLetter = a.priority === 'urgent' ? '(A)' : a.priority === 'high' ? '(B)' : '(C)';
            const status = a.completed ? 'x ' : '';
            const proj = `+${meeting.templateType.replace(/[^a-zA-Z0-9]/g, '')}`;
            const ctx = `@${a.assignee.toLowerCase().replace(/[^a-zA-Z0-9]/g, '') || 'nook'}`;
            return `${status}${priorityLetter} ${dateStr} ${a.task} ${ctx} ${proj} mtg:${meeting.id}`;
          });

          const content = lines.join('\n');
          const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
          const url = URL.createObjectURL(blob);
          const link = document.createElement('a');
          link.href = url;
          link.download = `todo-${meeting.id}.txt`;
          link.click();
          URL.revokeObjectURL(url);

          return { success: true, message: `Exported ${lines.length} action items to Todo.txt format!` };
        } catch (err: any) {
          return { success: false, message: `Todo.txt export failed: ${err.message}` };
        }
      },
    });

    // 3. Local Shortcuts / System URL Handler Plugin
    this.registerPlugin({
      id: 'plugin-shortcuts',
      name: 'System Shortcuts',
      description: 'Dispatches meeting summary via macOS/Windows URL schemes or local clipboard webhook.',
      icon: '⚡',
      execute: async (meeting: Meeting) => {
        try {
          const payload = JSON.stringify({
            title: meeting.title,
            template: meeting.templateType,
            date: new Date(meeting.startedAt).toISOString(),
            actionsCount: (meeting.actionItems || []).length,
            summary: meeting.executiveSummary,
          }, null, 2);

          // Attempt macOS Shortcuts protocol or fallback to clipboard
          const shortcutUrl = `shortcuts://run-shortcut?name=NookMeeting&input=text&text=${encodeURIComponent(meeting.title)}`;
          
          if (typeof window !== 'undefined' && 'open' in window && navigator.platform?.includes('Mac')) {
            window.open(shortcutUrl, '_blank');
          } else {
            await navigator.clipboard.writeText(payload);
          }

          return { success: true, message: 'Dispatched to Local Shortcuts / Copied webhook JSON to clipboard!' };
        } catch (err: any) {
          return { success: false, message: `Shortcuts dispatch failed: ${err.message}` };
        }
      },
    });
  }

  public registerPlugin(plugin: NookPlugin) {
    this.plugins.set(plugin.id, plugin);
  }

  public getPlugins(): NookPlugin[] {
    return Array.from(this.plugins.values());
  }

  public async runPlugin(pluginId: string, meeting: Meeting): Promise<{ success: boolean; message: string }> {
    const plugin = this.plugins.get(pluginId);
    if (!plugin) {
      return { success: false, message: `Plugin ${pluginId} not found.` };
    }
    return await plugin.execute(meeting);
  }
}

export const pluginEngine = new PluginEngine();
